apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-scanner
  labels:
    app: wallet-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-scanner
  template:
    metadata:
      labels:
        app: wallet-scanner
    spec:
      containers:
      - name: wallet-scanner
        image: gcr.io/YOUR_PROJECT_ID/wallet-scanner:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secrets
              key: bot-token
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: telegram-secrets
              key: chat-id
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: wallet-scanner-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallet-scanner-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
